#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Set Sublime Text as default editor
# https://www.sublimetext.com/docs/3/osx_command_line.html
export EDITOR='subl -w'

# Fix history search key bindings for vi mode
bindkey -M viins "^R" history-incremental-search-backward
bindkey -M vicmd "^R" history-incremental-search-backward
bindkey -M viins "^Q" history-incremental-search-forward
bindkey -M vicmd "^Q" history-incremental-search-forward
